language: php

php:
	- 7.3
	- 7.4
	- nightly

before_script:
	- travis_retry composer self-update
	- travis_retry composer update --no-interaction
	- travis_retry wget https://scrutinizer-ci.com/ocular.phar

script:
	- composer test

after_script:
	- php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml

matrix:
	fast_finish: true
